import './globals.css';
import { Header } from './Components/header';
import { Saira } from 'next/font/google';
import { FilterContextProvider } from './Context/filter-context';
import { DefaultProviders } from './Components/default-providers';

const saira = Saira({
  weight: ['300', '400', '500', '600'],
  subsets: ['latin'],
});

export const metadata = {
  title: 'capputeeno',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={saira.className}>
        <DefaultProviders>
          <Header />
          {children}
        </DefaultProviders>
      </body>
    </html>
  );
}
